name: BeefSPFog
version: 1.2.3
main: ru.whitebeef.beefspfog.BeefSPFog
api-version: 1.16
authors: [ _WhiteBeef_ , Xikki]
description: SP Fog
commands:
  fog:
    usage: /<command>
    description: Main fog command